CLASS LHC_ZCITR_CIT_LIB_DB_058058 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZcitrCitLibDb058058
        RESULT result.
ENDCLASS.

CLASS LHC_ZCITR_CIT_LIB_DB_058058 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
